namespace: my_own_namespace
name: yandex_cloud_elk
version: 1.0.0
readme: README.md
authors:
  - Your Name <your.email@example.com>
description: Collection with custom module and role
license:
  - GPL-3.0-or-later
tags:
  - file
  - module
dependencies: {}
repository: https://github.com/DimirDin/my_own_collection
